apiVersion: v1
kind: Service
metadata:
  name: nifi
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
    - name: remote
      port: 8081
    - name: https
      port: 8443
  selector:
    k8s-app: nifi


